import { getStore } from '@netlify/blobs';
const PRODUCTS={
  'almoravides-research':{price:'9.99',currency:'EUR',manualDelivery:true,title:'المرابطون — من الصحراء المغربية إلى بناء إمبراطورية'},
  idrissides:{price:'4.99',currency:'EUR',manualDelivery:false,title:'Idrissides youth book'},
  almoravides:{price:'4.99',currency:'EUR',manualDelivery:false,title:'Almoravides youth book'},
  almohades:{price:'4.99',currency:'EUR',manualDelivery:false,title:'Almohades youth book'},
  marinides:{price:'4.99',currency:'EUR',manualDelivery:false,title:'Marinides youth book'}
};
const ALLOWED_LANGS=['ar','fr','en','es','nl','it'];
const validEdition=(book,lang)=>Boolean(PRODUCTS[book])&&ALLOWED_LANGS.includes(lang)&&(book!=='almoravides-research'||lang==='ar');
function paypalConfig(){const sandbox=process.env.PAYPAL_ENV==='sandbox';if(!sandbox&&process.env.PAYPAL_ENV!=='live')throw new Error('PayPal is not enabled');const api=sandbox?'https://api-m.sandbox.paypal.com':'https://api-m.paypal.com';const id=sandbox?(process.env.PAYPAL_SANDBOX_CLIENT_ID||process.env.PAYPAL_CLIENT_ID):process.env.PAYPAL_CLIENT_ID;const secret=sandbox?(process.env.PAYPAL_SANDBOX_CLIENT_SECRET||process.env.PAYPAL_CLIENT_SECRET):process.env.PAYPAL_CLIENT_SECRET;if(!id||!secret)throw new Error('PayPal credentials are missing');return {api,id,secret}}
async function accessToken(){const {api,id,secret}=paypalConfig();const auth=Buffer.from(`${id}:${secret}`).toString('base64');const r=await fetch(`${api}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw new Error('Unable to authenticate with PayPal');return {api,token:(await r.json()).access_token}}
async function sendAdminNotification(order){const apiKey=process.env.RESEND_API_KEY||'',from=process.env.RESEND_FROM_EMAIL||'',to=process.env.ORDER_ADMIN_EMAIL||'oueledsanhaja@gmail.com';if(!apiKey||!from)throw new Error('Resend is not configured');const subject=`Paiement confirmé — ${order.productTitle} — ${order.amount} ${order.currency}`;const lines=[`Produit: ${order.productTitle}`,`Product ID: ${order.book}`,`Montant: ${order.amount} ${order.currency}`,`Date/heure: ${new Date(order.paidAt).toISOString()}`,`Client: ${order.customerName||'Non fourni'}`,`E-mail client: ${order.customerEmail||'Non fourni'}`,`PayPal order ID: ${order.orderID}`,`PayPal transaction ID: ${order.captureID}`,`Langue: ${order.lang}`,`Référence commande: ${order.orderReference}`];const text=lines.join('\n');const html=`<div style="font-family:Arial,sans-serif;line-height:1.55"><h2>Paiement Bawaba confirmé</h2>${lines.map(v=>`<p>${v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</p>`).join('')}</div>`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','Idempotency-Key':`bawaba-paypal-${order.captureID}`},body:JSON.stringify({from,to:[to],subject,text,html})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`Resend error ${r.status}`);return data.id||null}
async function issue(orderID,data){const resultStore=getStore('paypal-entitlements'),orderStore=getStore('paypal-orders');let existing=await resultStore.get(orderID,{type:'json'});if(existing){if(existing.book==='almoravides-research'&&existing.adminNotificationStatus!=='sent'&&existing.order){try{const emailID=await sendAdminNotification(existing.order);existing={...existing,adminNotificationStatus:'sent',adminNotificationID:emailID};await resultStore.setJSON(orderID,existing)}catch(e){existing={...existing,adminNotificationStatus:'failed',adminNotificationError:String(e.message||e).slice(0,300)};await resultStore.setJSON(orderID,existing)}}return existing}
  const pu=data.purchase_units?.[0],capture=pu?.payments?.captures?.find(item=>item.status==='COMPLETED'),[book,lang]=(pu?.custom_id||'').split(':'),product=PRODUCTS[book];
  if(data.status!=='COMPLETED'||!capture||!product||capture.amount?.currency_code!==product.currency||capture.amount?.value!==product.price||!validEdition(book,lang))throw new Error('Payment could not be verified');
  const payer=data.payer||{},customerName=[payer.name?.given_name,payer.name?.surname].filter(Boolean).join(' '),orderReference=pu?.invoice_id||`BAW-${orderID}`;const order={orderID,captureID:capture.id,book,lang,productTitle:product.title,amount:capture.amount.value,currency:capture.amount.currency_code,paidAt:Date.parse(capture.create_time||new Date().toISOString()),customerName,customerEmail:payer.email_address||'',orderReference,status:'COMPLETED'};await orderStore.setJSON(`order:${orderID}`,order);
  let result;if(product.manualDelivery){let adminNotificationStatus='pending',adminNotificationID=null,adminNotificationError=null;try{adminNotificationID=await sendAdminNotification(order);adminNotificationStatus='sent'}catch(e){adminNotificationStatus='failed';adminNotificationError=String(e.message||e).slice(0,300)}result={status:'COMPLETED',deliveryMode:'manual',book,lang,orderReference,adminNotificationStatus,adminNotificationID,adminNotificationError,order}}
  else{const entitlementToken=crypto.randomUUID()+crypto.randomUUID().replaceAll('-',''),expiresAt=Date.now()+7*24*60*60*1000;await getStore('ebook-entitlements').setJSON(entitlementToken,{book,lang,orderID,captureID:capture.id,expiresAt,downloads:0,maxDownloads:5});result={status:'COMPLETED',deliveryMode:'automatic',book,lang,downloadUrl:`/api/download?token=${encodeURIComponent(entitlementToken)}`,readerUrl:`/api/download?token=${encodeURIComponent(entitlementToken)}&mode=inline`,expiresAt,orderReference,order}}
  await resultStore.setJSON(orderID,result);return result}
export default async(req)=>{if(req.method!=='GET')return new Response('Method not allowed',{status:405});try{const orderID=new URL(req.url).searchParams.get('orderID');if(!orderID)return Response.json({error:'Missing order ID'},{status:400});const issued=await getStore('paypal-entitlements').get(orderID,{type:'json'});if(issued&&issued.adminNotificationStatus==='sent')return Response.json(issued);const {api,token}=await accessToken();let r=await fetch(`${api}/v2/checkout/orders/${encodeURIComponent(orderID)}`,{headers:{Authorization:`Bearer ${token}`}}),data=await r.json();if(!r.ok)return Response.json({error:'Unable to verify PayPal order'},{status:502});if(data.status==='APPROVED'){r=await fetch(`${api}/v2/checkout/orders/${encodeURIComponent(orderID)}/capture`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','PayPal-Request-Id':`bawaba-capture-${orderID}`}});data=await r.json();if(!r.ok)return Response.json({error:'Payment capture failed'},{status:502})}if(data.status==='COMPLETED')return Response.json(await issue(orderID,data));return Response.json({status:data.status})}catch(e){console.error(e);return Response.json({error:e.message},{status:500})}};
